alias: Мониторинг температуры гостиная
description: ""
triggers:
  - alias: Изменение температуры
    trigger: state
    entity_id:
      - sensor.ble_temperature_a4c1387e6730
      - input_number.kond_leto_maks
      - input_number.kond_leto_min
      - input_number.kond_zima_maks
      - input_number.kond_zima_min
    id: Изменение температуры
    enabled: true
  - alias: Балкон открыт 2 минуты
    trigger: state
    entity_id:
      - binary_sensor.okno_ili_dveri_dlia_konditsionera
    from: "off"
    to: "on"
    id: Балкон открыт 2 минуты
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - alias: Балкон закрыт
    trigger: state
    entity_id:
      - binary_sensor.okno_ili_dveri_dlia_konditsionera
    from: "on"
    to: "off"
    id: Балкон закрыт
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - trigger: state
    entity_id:
      - binary_sensor.zamok_contact
    from: "off"
    to: "on"
conditions: []
actions:
  - action: switch.turn_{{toggle}}
    metadata: {}
    data: {}
    target:
      entity_id: switch.konder_dlia_monitora
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - if:
      - condition: state
        entity_id: fan.ac_switch
        state: "on"
    then:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: "{{temp|int}}"
          hvac_mode: "{{mode}}"
        target:
          entity_id: climate.ac_fan
        enabled: true
      - action: climate.set_fan_mode
        metadata: {}
        data:
          fan_mode: "{{speed}}"
        target:
          entity_id: climate.ac_fan
variables:
  season: "{{ states('sensor.season') }}"
  on_sensor: binary_sensor.okno_ili_dveri_dlia_konditsionera
  lock: binary_sensor.zamok_contact
  outside_temp: "{{ state_attr('weather.pogoda','temperature')|float(20) }}"
  sum_max: "{{ states('input_number.kond_leto_maks') |float(28)}}"
  sum_min: "{{ states('input_number.kond_leto_min') |float(26)}}"
  wint_max: "{{ states('input_number.kond_zima_maks') |float(26)}}"
  wint_min: "{{ states('input_number.kond_zima_min') |float(24)}}"
  cur_temp: "{{ states('sensor.ble_temperature_a4c1387e6730')|float(0) }}"
  spring_max: >-
    {{ states('input_number.konditsioner_minimalnaia_temperatura_oseniu')
    |float(0)}}
  cr_temp: -5
  entity: climate.ac_fan
  mode: >-
    {% if season == 'winter' or (season in ['spring', 'autumn'] and cur_temp <
    wint_max) and outside_temp > -5 %}heat  

    {% elif season == 'summer' or (season in ['spring', 'autumn'] and
    outside_temp > spring_max)%}cool  

    {% else %}off {% endif %}
  toggle: |-
    {% if states(on_sensor) == 'off' and states(lock) == 'on' %}
      {% if season in ['winter', 'spring', 'autumn'] and outside_temp > cr_temp and outside_temp < spring_max%}
        {% if is_state(entity, 'off') %}   
        {{ 'on' if cur_temp < wint_min|float(0) else 'off' }}   
        {% else %}   
        {{ 'off' if cur_temp > wint_max|float(0) else 'on' }}   
        {% endif %}  
      {% elif season == 'summer' or (season in ['spring', 'autumn'] and outside_temp > spring_max) %}   
        {% if is_state(entity, 'off') %}   
        {{ 'on' if cur_temp > sum_max|float(0) else 'off' }}  
        {% else %}  
        {{ 'off' if cur_temp < sum_min|float(0) else 'on' }}
        {% endif %}  
      {% else %}off{% endif %} 
    {% else %}off{% endif %}
  speed: >-
    {% if season == 'summer' or (season in ['spring', 'autumn'] and outside_temp
    > spring_max) %}  
      {% if cur_temp > (sum_max|float(0) + 3) %}high  
      {% elif cur_temp > (sum_max|float(0) + 2) %}mid  
      {% else %}low{% endif %}
    {% elif season == 'winter' or (season in ['spring', 'autumn'] and cur_temp <
    wint_min) and outside_temp > cr_temp %} 
      {% if cur_temp < (wint_min|float(0) - 3) %}high  
      {% elif cur_temp < (wint_min|float(0) - 2) %}mid  
      {% else %}low{% endif %} 
    {% else %}low{% endif %}
  temp: "{% if mode == 'heat' %} 30 {% else %} 16 {% endif %}"
mode: single
